# permissions for end users to view recontests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: recontest-viewer-role
rules:
- apiGroups:
  - example.anirudh.io
  resources:
  - recontests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - example.anirudh.io
  resources:
  - recontests/status
  verbs:
  - get
