# permissions for end users to edit recontests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: recontest-editor-role
rules:
- apiGroups:
  - example.anirudh.io
  resources:
  - recontests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - example.anirudh.io
  resources:
  - recontests/status
  verbs:
  - get
